services:
  srs-vocabulary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: srs-vocabulary
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      PORT: 8000
    volumes:
      - ./logs:/app/logs
      - ./vocab_sets:/app/vocab_sets
    restart: unless-stopped
